<div>
    <div class="mb-6 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><h1 class="text-xl font-semibold text-gray-900 dark:text-white">Solicitudes de diseño</h1><p class="text-sm text-zinc-500 dark:text-zinc-400">Revisa y actualiza el estado de las peticiones de clientes.</p></div><select wire:model.live="status" class="rounded-lg border-zinc-300 bg-white text-sm dark:border-zinc-600 dark:bg-zinc-800"><option value="">Todos los estados</option>@foreach($statuses as $value => $label)<option value="{{ $value }}">{{ $label }}</option>@endforeach</select></div>
    <flux:table :paginate="$requests" bleed><flux:table.columns sticky><flux:table.column>Cliente</flux:table.column><flux:table.column>Solicitud</flux:table.column><flux:table.column>Preferencias</flux:table.column><flux:table.column>Estado</flux:table.column></flux:table.columns><flux:table.rows>
        @forelse($requests as $request)
            <flux:table.row :key="$request->id"><flux:table.cell>{{ $request->customer?->contact_name ?: $request->customer?->user?->name ?: '—' }}</flux:table.cell><flux:table.cell><div class="max-w-xs"><p class="font-medium">{{ $request->title }}</p><a class="text-xs text-blue-600 hover:underline" href="{{ $request->design_reference_url }}" target="_blank" rel="noopener noreferrer">Ver referencia</a></div></flux:table.cell><flux:table.cell class="text-sm">{{ $request->desiredSize?->name ?: 'Cualquier tamaño' }} · {{ $request->desiredFinish?->name ?: 'Cualquier acabado' }}<br>{{ $request->requested_quantity ? $request->requested_quantity.' stickers' : 'Cantidad por definir' }}</flux:table.cell><flux:table.cell><select wire:change="updateStatus({{ $request->id }}, $event.target.value)" class="rounded-lg border-zinc-300 bg-white text-sm dark:border-zinc-600 dark:bg-zinc-800">@foreach($statuses as $value => $label)<option value="{{ $value }}" @selected($request->status === $value)>{{ $label }}</option>@endforeach</select></flux:table.cell></flux:table.row>
        @empty
            <flux:table.row><flux:table.cell colspan="4" class="py-12 text-center">No hay solicitudes registradas.</flux:table.cell></flux:table.row>
        @endforelse
    </flux:table.rows></flux:table>
</div>
